# Generated by Django 6.0.3 on 2026-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_retakes',
            field=models.PositiveIntegerField(default=0, help_text='Max number of retakes allowed. 0 = unlimited.'),
        ),
    ]
