# Generated by Django 5.0.6 on 2026-03-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_max_retakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image displayed above the question text', null=True, upload_to='exam_questions/'),
        ),
    ]
