# Generated by Django 5.0.6 on 2026-03-22 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assignment_weight',
            field=models.PositiveIntegerField(default=30, help_text='% of final course grade from assignments'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_weight',
            field=models.PositiveIntegerField(default=70, help_text='% of final course grade from this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, help_text='Minimum % score to pass'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.JSONField(default=list, help_text='[{type, text, options?, correct_index?, points?}]'),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='null = no limit', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_retakes',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False, help_text='True when timer expired and backend auto-submitted')),
                ('is_submitted', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_index', models.PositiveIntegerField(help_text='0-based index into exam.questions')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open Answer')], max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, help_text='List of option strings for MCQ', null=True)),
                ('selected_index', models.IntegerField(blank=True, help_text='MCQ: which option the student chose', null=True)),
                ('text_answer', models.TextField(blank=True, help_text='Open: free-text answer')),
                ('correct_index', models.IntegerField(blank=True, null=True)),
                ('max_points', models.FloatField(help_text='Points this question is worth')),
                ('points_earned', models.FloatField(blank=True, help_text='null = not yet graded (open Q)', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='null for open / pending', null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exams.examattempt')),
            ],
            options={
                'db_table': 'question_responses',
                'ordering': ['question_index'],
                'unique_together': {('attempt', 'question_index')},
            },
        ),
    ]
