# Generated by Django 5.0.6 on 2026-03-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_grading_system'),
        ('exams', '0004_exam_assignment_weight_exam_exam_weight_and_more'),
    ]

    operations = [
    ]
