# Generated by Django 6.0.3 on 2026-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hls_path',
            field=models.CharField(blank=True, help_text='Relative path to index.m3u8 under MEDIA_ROOT', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_ready',
            field=models.BooleanField(default=False, help_text='True once FFmpeg transcoding is complete'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Original uploaded video file — transcoded to HLS by Celery', null=True, upload_to='videos/raw/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL — used when video_file is not set'),
        ),
    ]
