# Generated by Django 5.0.6 on 2026-03-18 20:56

import apps.courses.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_published_at_course_status_lesson_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.courses.models.attachment_upload_path)),
                ('name', models.CharField(help_text='Display name shown to students — defaults to original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes — set automatically on upload')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
