# Generated by Django 5.0.6 on 2026-03-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonattachment',
            name='name',
            field=models.CharField(blank=True, help_text='Display name. Defaults to original filename if left empty.', max_length=255),
        ),
    ]
