# Generated by Django 5.0.6 on 2026-03-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lessonattachment_name_lessonnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquestion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='courses.lesson'),
        ),
    ]
