# Generated by Django 5.0.6 on 2026-03-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonnote'),
        ('courses', '0008_alter_lessonquestion_author_and_more'),
    ]

    operations = [
    ]
